version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phan/phan
    versions:
    - 4.0.3
    - 4.0.4
